[package]
name = "rust"
version = "0.1.0"
authors = ["Florian B <yuuki@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"

[[bin]]
name = "aoc"
path = "src/main.rs"

[lib]
name = "aoc_lib"
path = "src/lib.rs"
